const address = '89.235.236.175'
export const REST_SERVICE = 'http://' + address + ':3000'
export const WEBCAM1_SERVICE = 'http://' + address + ':3001/video_feed'
export const WEBCAM2_SERVICE = 'http://' + address + ':3002/video_feed'
export const SPECTROMETER_SERVICE = 'ws://' + address + ':3005/'
